### ISSUE TITLE
Possible to limit gestures to the child widget?

### ISSUE THREAD

**Issue by doppio** [fireslime/photo_view#325]
I'm trying to limit gestures to the actual content of the child. In other words, I don't want the user to be able to start pinch/pan gestures outside of the bounds of the child. For my use case, I'm trying to create a stack of PhotoViews, so the user can manipulate several different widgets to reposition/resize/rotate them. Touches that don't intersect with the PhotoView's child should pass through to the next "layer". Does this package support this, out of the box?

I tried passing in a gestureDetectorBehavior of HitTestBehaviour.transluscent, but that doesn't seem to do the trick.

**Comment by renancaraujo** [comment]
Use [`disableGestures`](https://pub.dev/documentation/photo_view/latest/photo_view/PhotoView/disableGestures.html) and wrap your custom child with an inner gesture detector that interacts with a controller

**Comment by renancaraujo** [comment]
After some evaluation, this is a very hard thing to achieve. 

For now, the gesture detector wraps the outer container, making `PhotoViewCore` handle the gestures coordinates from a stable point o view. 
Wrapping the gesture detector around the children would make these coordinates be affected by the current state of the children.

There is nothing on the package that supports this for now. 

You can achieve this effect by doing what I said [here](https://github.com/fireslime/photo_view/issues/325#issuecomment-679104115), but have in mind that you will need to constantly convert the coordinates from scale, double-tap, and single tap gestures to a static position.

It is possible, but since it is a very specific feature, I don't think we can prioritize this.

**Comment by doppio** [comment]
Fair enough. Thank you for looking into it!
